name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: false
    
    - name: Sonar Report
      run: mvn verify sonar:sonar
      env:
        GITHUB_TOKEN: ${{ github.token }} 
        
    - name: upload report
      uses: actions/upload-artifact@v1
      with:
        name: Tests Results
        path: target/site/
      continue-on-error: true 
